#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: astepovy <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/09/15 12:06:35 by astepovy          #+#    #+#              #
#    Updated: 2016/09/15 12:06:43 by astepovy         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = ft_display_file
CC = gcc
CFLAGS = -Wall -Wextra -Werror

all: $(NAME)

$(NAME):
	$(CC) $(CFLAGS) -o $(NAME)  main.c

clean:
	rm -f $(NAME)

fclean: clean